/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  TodoItem,
} from './models/todoItem';


export namespace Components {

  interface MyApp {}
  interface MyAppAttributes extends StencilHTMLAttributes {}

  interface TodoApp {}
  interface TodoAppAttributes extends StencilHTMLAttributes {}

  interface TodoListForm {
    'todoItemsLength': number;
  }
  interface TodoListFormAttributes extends StencilHTMLAttributes {
    'onInputChange'?: (event: CustomEvent) => void;
    'onSubmit'?: (event: CustomEvent) => void;
    'todoItemsLength'?: number;
  }

  interface TodoList {
    'todoItems': TodoItem[];
  }
  interface TodoListAttributes extends StencilHTMLAttributes {
    'todoItems'?: TodoItem[];
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyApp': Components.MyApp;
    'TodoApp': Components.TodoApp;
    'TodoListForm': Components.TodoListForm;
    'TodoList': Components.TodoList;
  }

  interface StencilIntrinsicElements {
    'my-app': Components.MyAppAttributes;
    'todo-app': Components.TodoAppAttributes;
    'todo-list-form': Components.TodoListFormAttributes;
    'todo-list': Components.TodoListAttributes;
  }


  interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {}
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };

  interface HTMLTodoAppElement extends Components.TodoApp, HTMLStencilElement {}
  var HTMLTodoAppElement: {
    prototype: HTMLTodoAppElement;
    new (): HTMLTodoAppElement;
  };

  interface HTMLTodoListFormElement extends Components.TodoListForm, HTMLStencilElement {}
  var HTMLTodoListFormElement: {
    prototype: HTMLTodoListFormElement;
    new (): HTMLTodoListFormElement;
  };

  interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {}
  var HTMLTodoListElement: {
    prototype: HTMLTodoListElement;
    new (): HTMLTodoListElement;
  };

  interface HTMLElementTagNameMap {
    'my-app': HTMLMyAppElement
    'todo-app': HTMLTodoAppElement
    'todo-list-form': HTMLTodoListFormElement
    'todo-list': HTMLTodoListElement
  }

  interface ElementTagNameMap {
    'my-app': HTMLMyAppElement;
    'todo-app': HTMLTodoAppElement;
    'todo-list-form': HTMLTodoListFormElement;
    'todo-list': HTMLTodoListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
