/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  TodoItem,
} from './models/todoItem';

declare global {

  namespace StencilComponents {
    interface MyApp {

    }
  }

  interface HTMLMyAppElement extends StencilComponents.MyApp, HTMLStencilElement {}

  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-app': JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface TodoApp {

    }
  }

  interface HTMLTodoAppElement extends StencilComponents.TodoApp, HTMLStencilElement {}

  var HTMLTodoAppElement: {
    prototype: HTMLTodoAppElement;
    new (): HTMLTodoAppElement;
  };
  interface HTMLElementTagNameMap {
    'todo-app': HTMLTodoAppElement;
  }
  interface ElementTagNameMap {
    'todo-app': HTMLTodoAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'todo-app': JSXElements.TodoAppAttributes;
    }
  }
  namespace JSXElements {
    export interface TodoAppAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface TodoListForm {
      'todoItemsLength': number;
    }
  }

  interface HTMLTodoListFormElement extends StencilComponents.TodoListForm, HTMLStencilElement {}

  var HTMLTodoListFormElement: {
    prototype: HTMLTodoListFormElement;
    new (): HTMLTodoListFormElement;
  };
  interface HTMLElementTagNameMap {
    'todo-list-form': HTMLTodoListFormElement;
  }
  interface ElementTagNameMap {
    'todo-list-form': HTMLTodoListFormElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'todo-list-form': JSXElements.TodoListFormAttributes;
    }
  }
  namespace JSXElements {
    export interface TodoListFormAttributes extends HTMLAttributes {
      'onInputChange'?: (event: CustomEvent) => void;
      'onSubmit'?: (event: CustomEvent) => void;
      'todoItemsLength'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface TodoList {
      'todoItems': TodoItem[];
    }
  }

  interface HTMLTodoListElement extends StencilComponents.TodoList, HTMLStencilElement {}

  var HTMLTodoListElement: {
    prototype: HTMLTodoListElement;
    new (): HTMLTodoListElement;
  };
  interface HTMLElementTagNameMap {
    'todo-list': HTMLTodoListElement;
  }
  interface ElementTagNameMap {
    'todo-list': HTMLTodoListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'todo-list': JSXElements.TodoListAttributes;
    }
  }
  namespace JSXElements {
    export interface TodoListAttributes extends HTMLAttributes {
      'todoItems'?: TodoItem[];
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
